language: php
addons:
  sonarcloud:
    organization: hardyantz-github
    token:
      secure: KhhxivxEIhYoP9DJPOVKrHWQ7F4gKP/sb+5jm2ihwz7YggnMw6M16CkgxhdI3ubSAJ5wPEbjHVVMpoPCxkTmsOzeXFSKdl54zw1i+Z+rVm/oAr74kcFB7gsUTYHKaRM/zrV7fWRutsElLe+4A7wNFTMQljj94m9lUkLOTERUr1Y89zBUar0cFzzegi+F4/5vecsEV5r9a4HQSmKJfi+uj9O+549SsFhZt9qj+dR8iI9EUE7WqXdA79+GekS1hT6emyieC+Bo2Viw9r09KGq6q3IyvpnzgQ5tP6Ciqa4YkH5FB3mhGKks71su0b6vI5T6/pjMhRBJ2yNoc2KsIGB8zk+EoBAxBK5x6svoKsbyLcQZ4DEpMrWlWeiP6HZzMdYJw08rfioMT2h2AeWsfVBf2PVV+IdeJfLX8gZIeYQkPk/9NSOATP/GIGnWvILnN5IS0Fc+au+DKHoSW5mFudbRk0Fdx0FhxO65++i50PsWEZ8dH6ZLaB0gqQWLm0JK+AiJGYjimUFN7QC7Ehjkml7pHoAkcqoRKKl5MrHnSaPJVPwGn7mdeT1wSw8rz7ebvuBWviiHrNoCGQ8qZXEoLUm5Eob1m0/aQ3vsoILYnDk3/tAvH1s6ytOxPnTphj9f25GgpsFrAmH24MUDMUFekxfE+2Xe8QaEUCijEyx2WZEtlpI=
    github_token:
      secure: cq86l476PXfPJzbeir8fAPES636E7Ge6TlET5rp5PxyXZCbMVrne0MlpQgeCA+5iNlsssPSB6vXuKcN296exYFeFKRozGPmzZGUpUFl0zv4EfAokHjVqIibAZ9MbDhiSX0ZnQ5rWfGbIfNMhcvKG/yOyl5cw+DF5n9NO4u6bA9cGEAnKm0ONuPD3zkyjSHv4c7+cUsjP5C0f3+RMK3mgV6FbYC/ZwuM1Icq5xN7C02ZBPKhYJtmFNchj3RP6XP8QInebTHwl2p4etI41eP3I1QRQHYrWA1DCJ9BpQo44yE7WwfzuZj9f7pQiXxvpqqGsqhypqi6lsNb5OQu492WKrMQTpYvqkvCuf8Y3P73yranzqHcm70QUkoGFpxp/k+vwzdGFqKyIyvI2B5hgefeFGPtV690WTHacVcu1TIHyMGdMYdkV/VmbNY4+PJILIcSZT7kjokzJ3bJVL2Xe0GxqE61AwuKrVwfX4WPWWUki/qKjuZTuYj2sWt3hxLXnyZOghcjOB+2htv11xCJifdR7kS8rQjsGNe1V+8xLibck5HaoMqCwj08Nm4qIUPmFq6zEyXZiswxd066luGemMhqVtOm9U6+dkMWH3nAa91OV3apzH4/yw5A5GEGXHHeE9jcvbq9+Fk3iddFyUbsK1cuiA5XzRC4K2t8/Z+levXjf7z8=
jdk:
- oraclejdk8
script:
- sonar-scanner
cache:
  directories:
  - "$HOME/.sonar/cache"
notifications:
  slack:
    rooms:
      - hardyantzcorp:VjbEAi5nWM1HXSHZwhhsyqQa#general
      - hardyantzcorp:VjbEAi5nWM1HXSHZwhhsyqQa#random
